title: dr3amda3mon's dungeon of dreams
email: al.9000log@protonmail.com
author: 0xdr3am
description: >-
  cybersecurity blog and ctf writeups
baseurl: ""
url: https://0xdr3am.github.io
github_username:  0xdr3am

show_downloads: false
google_analytics: UA-161626775-1

theme: jekyll-theme-hacker
plugins:
  - jekyll-paginate
  #- jekyll-feed
paginate: 5
